# Generated by Django 3.2.7 on 2021-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='eaddr',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='esal',
            field=models.FloatField(),
        ),
    ]
